app/Http/routes.php
<?php

/*
    Admin panel
*/

Route::get('hosts/{hostname}', function(Request $request, $hostname) {
    $file = File::get(storage_path() . '/Metadata.js');
    return response()->json(json_decode($file));
});

Route::get('hosts/{hostname}/probes', function(Request $request, $hostname) {
    $file = File::get(storage_path() . '/Probes.js');
    return response()->json(json_decode($file));
});

Route::group(['prefix' => 'admin'], function() {
    
    Route::get('/', ['as' => 'home', 'uses' => 'PageController@index']);

    // Route::get('/', function() {
    //     return redirect()->route('admin.session.create');
    // });

    // Route::resource('session', 'SessionController', ['only' => ['create', 'store', 'destroy']]);
    // Route::resource('user', 'UserController', ['only' => ['create', 'store']]);

    // Route::group(['middleware' => 'auth'], function() {
        // Route::resource('user', 'UserController');
        Route::resource('site', 'SiteController');
        Route::get('site/{id}/click', ['as' => 'admin.site.click', 'uses' => 'SiteController@click']);
        Route::get('site/{id}/form', ['as' => 'admin.site.form', 'uses' => 'SiteController@form']);
        Route::get('site/{id}/code', ['as' => 'admin.site.code', 'uses' => 'SiteController@code']);
    // });

});


/*
    API.
*/

Route::group(['prefix' => 'api'], function() {

    Route::group(['prefix' => 'click'], function() {
        Route::post('init', 'Api\ClickController@init');
        Route::post('save', 'Api\ClickController@save');
        Route::post('screenshot', 'Api\ClickController@screenshot');
    });

    Route::group(['prefix' => 'form'], function() {
        Route::post('init', 'Api\FormController@init');
        Route::post('save', 'Api\FormController@save');
    });
    
    Route::get('token', 'Api\ApiController@token');

});


/*
    Examples.
*/

Route::group(['prefix' => 'example'], function() {

    Route::get('first', function() {
        return response()->view('examples.first');
    });
    Route::get('second', function() {
        return response()->view('examples.second');
    });

});

app/Site.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

use App\Breakpoint;
use App\Visit;
use App\FormAction;
use App\FormEvent;
use App\FormLabel;

class Site extends Model {

    protected $fillable = ['track_id', 'user_id', 'base_url'];


    public function points() {
        return $this->hasMany(Point::class);
    }

    public function scrolls() {
        return $this->hasMany(Scroll::class);
    }

    public function breakpoints() {
        return $this->hasMany(Breakpoint::class);
    }

    public function formActions() {
        return $this->hasMany(FormAction::class);
    }

    public function formLabels() {
        return $this->hasMany(FormLabel::class);
    }

    public function hasAllScreenshots($width) {
        $breakpoints = $this->breakpoints;
        $result = [];

        foreach($breakpoints as $breakpoint) {
            if($width >= $breakpoint->min_width && $width <= $breakpoint->max_width && !$breakpoint->has_image) {
                return false;
            }
        }

        return true;
    }

    public function breakpointsByWidth($width) {
        $breakpoints = $this->breakpoints;
        $result = [];

        foreach($breakpoints as $breakpoint) {
            if($width >= $breakpoint->min_width && $width <= $breakpoint->max_width && !$breakpoint->has_image) {
                $result[] = $breakpoint;
            }
        }

        return $result;
    }

    public function getPointsByType($type) {
        return Point::where('site_id', $this->id)->where('type', $type)->get();
    }

    public function pointsByResolution($resolution, $type) {
        if(!$resolution['min']) $resolution['min'] = 0;
        if(!$resolution['max']) $resolution['max'] = PHP_INT_MAX;

        $points = Point::where('site_id', $this->id)->where('type', $type)->whereBetween('width', [$resolution['min'], $resolution['max']])->get(['x', 'y', 'width']);

        foreach($points as $point) {
            $point->x = Point::countPositionByCenter($point->x, $point->width);
        }

        return $points;
    }

    public function scrollsByResolution($resolution) {
        if(!$resolution['min']) $resolution['min'] = 0;
        if(!$resolution['max']) $resolution['max'] = PHP_INT_MAX;

        $scrolls = Scroll::where('site_id', $this->id)->whereBetween('width', [$resolution['min'], $resolution['max']])->get(['y', 'height']);

        return $scrolls;
    }


    /*
        Returns forms' statistics binded to current site object.
        Counts min, max, average and median time for each field
        Counts number of trials per visit fot each field
        Creates histogram for each field

        result:
        [{
            action:     FormAction object
            labels:     [
                0 => {
                    label:      FormLabel object,
                    min:        min time (float)
                    max:        max time (float)
                    avg:        average time (float)
                    median:     median time (float)
                    histogram:  array 
                }
            ]
        }, { action, labels }, {...} ]
    */

    public function formStatistics() {
        $result = [];
        $actions = $this->formActions;

        foreach($actions as $action) {

            $formLabels = $action->getFormLabels();
            $labels = [];

            foreach($formLabels as $label) {
                $labels[] = [
                    'label'         => $label,
                    'statistics'    => $label->statistics()
                ];
            }

            $result[] = [
                'action'    => $action,
                'labels'    => $labels
            ];
        }

        return $result;
    }


}

app/Http/Controllers/SiteController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Breakpoint;
use App\Point;
use App\Scroll;
use App\Site;
use App\User;
use App\Visit;
use App\Module;
use App\FormLabel;
use App\FormEvent;
use App\FormAction;

class SiteController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$mouse = Site::where('module_id', Module::MOUSE)->get();
		$form = Site::where('module_id', Module::FORM)->get();
        return response()->view('pages.site.index', compact('mouse', 'form'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create(Request $request)
	{
		$modules = Module::lists('name', 'id');
		return response()->view('pages.site.create', compact('modules'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		\DB::beginTransaction();
		try {
			$site = new Site();
			$site->url = $request->input('url');
			$site->module_id = (int)$request->input('module_id');
			$site->user_id = 1;
			$site->title = \Input::get('title');
			$site->save();

			if(!$site) {
				throw new \Exception('Site was not created');
			}

			if($site->module_id === Module::MOUSE) {

				$breakpoints_min = array_map(function($el) { return (int)$el; }, $request->input('breakpoint_min'));
				$breakpoints_max = array_map(function($el) { return (int)$el > 0 ? (int)$el : Breakpoint::MAX_WIDTH; }, $request->input('breakpoint_max'));
				$breakpoints = count($breakpoints_min);

				for($i = 0; $i < $breakpoints; ++$i) {
					$breakpoint = new Breakpoint();
					$breakpoint->site_id = $site->id;
					$breakpoint->min_width = $breakpoints_min[$i];
					$breakpoint->max_width = $breakpoints_max[$i];
					$breakpoint->has_image = false;
					$breakpoint->save();

					if(!$breakpoint) {
						throw new \Exception('Breakpoint ' . ($i + 1) . ' was not created');
					}
				}
			}

			$site->track_id = sha1($site->id);
			$site->save();

			\DB::commit();
			return redirect()->route('admin.site.code', [$site->id]);
		}
		catch(\Exception $e) {
			\DB::rollback();
			dd($e);
		}
	}

	/**
	 * Display site tracked by 'MouseTracker' module.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function click(Request $request, $id)
	{
		$site = Site::where('id', $id)->with('breakpoints')->first();
		$breakpoint_id = (int)$request->input('breakpoint', null);
		$breakpoint = $breakpoint_id ? Breakpoint::where('id', $breakpoint_id)->where('site_id', $site->id)->first() : null;

		if($breakpoint) {
			$resolution = [
				'min' => $breakpoint->min_width,
				'max' => $breakpoint->max_width
			];
			$points = json_encode($site->pointsByResolution($resolution, Point::Click));
			$moves = json_encode($site->pointsByResolution($resolution, Point::Move));
			$scrolls = json_encode($site->scrollsByResolution($resolution));
		}
		else {
			$resolution = ['min' => 0, 'max' => Breakpoint::MAX_WIDTH];
			$points = '';
			$moves = '';
			$scrolls = '';
		}

		$breakpoints = $site->breakpoints->lists('name', 'id');

        return response()->view('pages.site.click', compact('site', 'points', 'scrolls', 'moves', 'breakpoint', 'breakpoints'));
	}

	/**
	 * Display site tracked by 'FormTracker' module.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function form(Request $request, $id)
	{
		$site = Site::where('id', $id)->first();
		$statistics = $site->formStatistics();

        return response()->view('pages.site.form', compact('site', 'statistics'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit(Request $request, $id)
	{
		$site = Site::where('id', $id)->with('breakpoints')->first();
		$modules = Module::lists('name', 'id');
		$max_width = Breakpoint::MAX_WIDTH;

		return response()->view('pages.site.edit', compact('site', 'modules', 'max_width'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$site = Site::where('id', $id)->first();
		
		if(!$site) {
			throw new \Exception('Site not found');
		}

		$site->url = $request->input('url');
		$site->module_id = (int)$request->input('module_id');
		$site->title = \Input::get('title');
		$site->save();

		if($site->module_id === Module::MOUSE) {
			$breakpoints_id = array_map(function($el) { return (int)$el; }, $request->input('breakpoint_id'));
			$breakpoints_min = array_map(function($el) { return (int)$el; }, $request->input('breakpoint_min'));
			$breakpoints_max = array_map(function($el) { return (int)$el > 0 ? (int)$el : Breakpoint::MAX_WIDTH; }, $request->input('breakpoint_max'));
			$breakpoints = count($breakpoints_min);

			for($i = 0; $i < $breakpoints; ++$i) {
				if($breakpoints_id[$i] > 0) {
					$breakpoint = Breakpoint::where('id', $breakpoints_id[$i])->first();
				}
				else {
					$breakpoint = new Breakpoint();
					$breakpoint->has_image = false;
					$breakpoint->site_id = $site->id;
				}
				$breakpoint->min_width = $breakpoints_min[$i];
				$breakpoint->max_width = $breakpoints_max[$i];
				$breakpoint->save();

				if(!$breakpoint) {
					throw new \Exception('Breakpoint ' . ($i + 1) . ' was not created');
				}
			}
		}
		else {
			Breakpoint::where('site_id', $site->id)->delete();
		}

		\DB::commit();
		return redirect()->route('admin.site.index')->with('information', 'Site ' . $site->title . ' modified');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy(Request $request, $id)
	{
		$site = Site::where('id', $id)->first();

		$breakpoints = Breakpoint::where('site_id', $id);
		$breakpointsCollection = $breakpoints->get();
		$breakpoints->delete();

		foreach($breakpointsCollection as $breakpoint) {
			$path = './uploads/' . $breakpoint->id . '.png';
			if($breakpoint->has_image && \File::exists($path)) {
				\File::delete($path);
			}
		}

		FormAction::where('site_id', $id)->delete();
		FormEvent::where('site_id', $id)->delete();
		FormLabel::where('site_id', $id)->delete();
		Point::where('site_id', $id)->delete();
		Scroll::where('site_id', $id)->delete();
		Site::destroy($id);

		return redirect()->route('admin.site.index')->with('information', 'Site ' . $site->title . ' deleted');
	}


	public function code(Request $request, $id)
	{
		$site = Site::where('id', $id)->first();
        return response()->view('pages.site.code', compact('site'));
	}

}

resources/views/pages/site/click.blade.php
@extends('layouts.admin')

@section('meta.title') - Sites - Details @stop

@section('header.title')
    <a href='{{ route('admin.site.index') }}' class='sub'>Sites</a>
    <span class='sub'>{{ $site->title }}</span>
@stop

@section('header.settings')
    @parent
@stop

@section('header.navigation')

    <ul id='maps-tabs'>
        <li><a href='#screenshot' data-canvas=''>Screenshot</a></li>
        <li><a href='#clicks-heatmap' data-canvas='clicks-heatmap'>Click Heatmap</a></li>
        <li><a href='#clicks-confetti' data-canvas='clicks-confetti'>Click Confetti</a></li>
        <li><a href='#moves-heatmap' data-canvas='moves-heatmap'>Moves Heatmap</a></li>
        <li><a href='#scroll-heatmap' data-canvas='scroll-heatmap'>Scroll Heatmap</a></li>
    </ul>

@stop

@section('content.before')

    <form method='get' action='{{ route('admin.site.click', $site->id) }}' class='filters'>
        <div class='filter width'>
            <span class='label'>Breakpoint:</span>
            <span class='controls'>
                {!! Form::select('breakpoint', [null => 'All points'] + $breakpoints, $breakpoint ? $breakpoint->id : null, ['class' => 'small']) !!}
            </span>
        </div>
        <div class='filter confirm'>
            <span class='label'>&nbsp;</span>
            <span class='controls'>
                <input type='submit' value='Zatwierdź'>
            </span>
        </div>

        <button id='export'>Export as PNG</button>
    </form>

@stop

@section('content.class')
    full-width
@stop

@section('content')

    <div class='map'>
        @if($breakpoint)
            <img src='{{ asset('uploads/' . $breakpoint->id . '.png') }}' alt='' id='preview'>
        @else
            <h2>Choose breakpoint to see visualizations.</h2>
        @endif
        <canvas id='graph-clicks-heatmap' class='hidden'></canvas>
        <canvas id='graph-moves-heatmap' class='hidden'></canvas>
        <canvas id='graph-clicks-confetti' class='hidden'></canvas>
        <canvas id='graph-scroll-heatmap' class='hidden'></canvas>
        <div class='loading hidden'>
            <p class='loading-text'>
                Trwa generowanie... Proszę czekać...
            </p>
        </div>
    </div>

@stop


@section('footer.javascripts')

    <script src='https://code.jquery.com/jquery-1.12.3.min.js'></script>
    <script src='{{ asset('js/VisualizationClick.js') }}'></script>
    <script>

        var points      = JSON.parse('{!! $points !!}'),
            scrolls     = JSON.parse('{!! $scrolls !!}'),
            moves       = JSON.parse('{!! $moves !!}'),
            preview     = document.getElementById('preview'),
            $map        = $('.map'),
            $loading    = $map.find('.loading');

        $('#maps-tabs a').on('click', function(e) {

            var $this = $(this),
                func = $this.attr('href'),
                isGenerated = !!$this.data('generated'),
                canvasName = $this.data('canvas');

            if(canvasName.length === 0) {
                $map.find('canvas').addClass('hidden');
                return;
            }

            if(isGenerated) {
                $map
                    .find('canvas')
                        .addClass('hidden')
                        .end()
                    .find('#graph-' + canvasName)
                        .removeClass('hidden');

                return;
            }
            
            var canvas = document.getElementById('graph-' + canvasName);
            $loading.removeClass('hidden');

            setTimeout(function() {
                switch(func) {
                    case '#clicks-heatmap':
                        ClickVisualization.init({
                            points:     points,
                            preview:    preview,
                            canvas:     canvas,
                            setType:    'clicks'
                        });
                        ClickVisualization.drawHeatmap();
                    break;

                    case '#moves-heatmap':
                        ClickVisualization.init({
                            points:     moves,
                            preview:    preview,
                            canvas:     canvas,
                            setType:    'moves'
                        });
                        ClickVisualization.drawHeatmap();
                    break;

                    case '#clicks-confetti':

                        ClickVisualization.init({
                            points:     points,
                            preview:    preview,
                            canvas:     canvas,
                            setType:    'clicks'
                        });
                        ClickVisualization.drawConfetti();
                    break;

                    case '#scroll-heatmap':
                        ClickVisualization.init({
                            points:     scrolls,
                            preview:    preview,
                            canvas:     canvas,
                            setType:    'scrolls'
                        });
                        ClickVisualization.drawScrollHeatmap();
                    break;

                    default:
                        
                    break;
                }

                $this.attr('data-generated', true);
                $map
                    .find('canvas')
                        .addClass('hidden')
                        .end()
                    .find('#graph-' + canvasName)
                        .removeClass('hidden');

                $loading.addClass('hidden');

            }, 30);

        });  


        /*
            Exports heatmap and screenshot as PNG file.
            eg.: exportMap(preview, canvas, .3);
            
            param preview   <img> element with screenshot
            param canvas    <canvas> element with heatmap
            param alpha     alpha channel of heatmap 
        */

        $('#export').on('click', function(e) {

            e.preventDefault();
            var canvas = $('.map').find('canvas:not(.hidden)').get(0);
            exportMap(preview, canvas, .3);

        });

        function exportMap(preview, canvas, alpha) {

            var save = document.createElement('canvas'), 
                ctx = save.getContext('2d');

            save.width = preview.width;
            save.height = preview.height;
            ctx.drawImage(preview, 0, 0);

            var imageData = ctx.getImageData(0, 0, save.width, save.height),
                imageDataArray = imageData.data,
                heatmapDataArray = canvas.getContext('2d').getImageData(0, 0, save.width, save.height).data;

            for(var y = 0; y < save.height; ++y) {
                for(var x = 0; x < save.width; ++x) {

                    var index = (y * save.width + x) * 4;
                    for(var k = 0; k < 4; ++k) {
                        imageDataArray[index + k] = parseInt(alpha * imageDataArray[index + k] + (1 - alpha) * heatmapDataArray[index + k]);
                    }

                }
            }

            ctx.putImageData(imageData, 0, 0);

            window.open(save.toDataURL('image/png'));

        }

    </script>

@stop

resources/views/pages/site/code.blade.php
@extends('layouts.admin')

@section('meta.title') - Sites - Tracking code @stop

@section('header.title')
    <a href='{{ route('admin.site.index') }}' class='sub'>Sites</a>
    <span class='sub'>{{ $site->title }}</span>
@stop

@section('header.settings')
    @parent
@stop

@section('content')
    <h1>Tracking code</h1>

    <p>To install tracking script on your page copy code below and paste it anywhere in your site's code (preferably at the bottom of the page, just before <code>&lt;/body&gt;</code>.</p>

    @if($site->module_id === \App\Module::MOUSE)

    <pre>(function(tid, turl, surl) {
    var script = document.createElement('script');
    script.src = surl + 'js/MouseTracker.js';
    document.getElementsByTagName('head')[0].appendChild(script);
    script.onload = function() {
        MouseTracker.setup(tid, turl, surl);
    };
}('{{ $site->track_id }}', '{{ $site->url }}', '{{ url('/') . '/' }}'));</pre>
    
    @elseif($site->module_id === \App\Module::FORM)

    <pre>(function(tid, turl, surl) {
    var script = document.createElement('script');
    script.src = surl + 'js/FormTracker.js';
    document.getElementsByTagName('head')[0].appendChild(script);
    script.onload = function() {
        FormTracker.setup(tid, turl, surl);
    };
}('{{ $site->track_id }}', '{{ $site->url }}', '{{ url('/') . '/' }}'));</pre>

    @endif

@stop

resources/views/pages/site/create.blade.php
@extends('layouts.admin')

@section('meta.title') - Sites - Add site @stop

@section('header.title')
    <a href='{{ route('admin.site.index') }}' class='sub'>Sites</a>
@stop

@section('content')

    <h1>Add site</h1>

    <form method='post' action='{{ route('admin.site.store') }}' class='form'>
        <input type='hidden' name='_token' value='{{ Session::token() }}'>

        <div class='field'>
            <label for='url'>Site url (without &quot;http://&quot;):</label>
            <input type='text' id='url' name='url' value='' placeholder='eg. google.com' required>
        </div>

        <div class='field'>
            <label for='title'>Title (displayed only in admin panel):</label>
            <input type='text' id='title' name='title' value='' placeholder='eg. Contact page at my homepage' required>
        </div>

        <div class='field'>
            <label for='module_id'>Module (you can add more modules by creating new sites):</label>
            {!! Form::select('module_id', [null => 'Module'] + $modules, null, ['id' => 'module', 'required']) !!}
        </div>

        <div class='field breakpoints hidden'>
            <label>Breakpoints (pixels):</label>
            
            <div class='breakpoints-list'>
            </div>

            <div>
                <button class='button breakpoints-add'>Add breakpoint</button>
            </div>
        </div>

        <div class='field separated'>
            <input type='submit' value='Save'>
        </div>
    </form>

    <div class='breakpoints-form' style='display:none;' id='breakpoints-template'>
        <button class='remove' aria-label='Delete breakpoint'>&times;</button>
        <input type='number' name='breakpoint_min[]' placeholder='eg. 720'><span class='unit'>px</span>&nbsp;<span class='dash'>&ndash;</span>&nbsp;<input type='number' name='breakpoint_max[]' placeholder='eg. 1260'><span class='unit'>px</span>
    </div>

@stop


@section('footer.javascripts')

    <script src='https://code.jquery.com/jquery-1.12.3.min.js'></script>
    <script>

        var $field      = $('.field.breakpoints'),
            $list       = $('.breakpoints-list'),
            $template   = $('#breakpoints-template');

        $('#module').on('change', function(e) {
            var module = $(this).find('option:selected').text();
            if(module === 'MouseTracker') {
                $field.removeClass('hidden');
            }
            else {
                $field.addClass('hidden');
            }
        });

        $('.breakpoints-add').on('click', function(e) {
            e.preventDefault();

            $template
                .clone()
                .removeAttr('id')
                .css('display', 'block')
                .appendTo($list);
        });

        $list.on('click', '.remove', function(e) {
            e.preventDefault();
            $(this).parents('.breakpoints-form').remove();
        });
    </script>
@stop

resources/views/pages/site/edit.blade.php
@extends('layouts.admin')

@section('meta.title') - Sites - Edit site @stop

@section('header.title')
    <a href='{{ route('admin.site.index') }}' class='sub'>Sites</a>
@stop

@section('content')

    <h1>Edit site</h1>

    {!! Form::open(['url' => route('admin.site.update', $site->id), 'method' => 'patch', 'class' => 'form']) !!}
        <div class='field'>
            <label for='url'>Site url (without &quot;http://&quot;):</label>
            <input type='text' id='url' name='url' value='{{ $site->url }}' placeholder='eg. google.com' required>
        </div>

        <div class='field'>
            <label for='title'>Title (displayed only in admin panel):</label>
            <input type='text' id='title' name='title' value='{{ $site->title }}' placeholder='eg. Contact page at my homepage' required>
        </div>

        <div class='field'>
            <label for='module_id'>Module (you can add more modules by creating new sites):</label>
            {!! Form::select('module_id', [null => 'Module'] + $modules, $site->module_id, ['i
            d' => 'module', 'required']) !!}
        </div>

        <div class='field breakpoints {{ $site->module_id === App\Module::MOUSE ? '' : 'hidden' }}'>
            <label>Breakpoints (pixels):</label>
            
            <div class='breakpoints-list'>
                @foreach($site->breakpoints as $breakpoint)
                    <div class='breakpoints-form'>
                        <button class='remove' aria-label='Delete breakpoint'>&times;</button>
                        <input type='hidden' name='breakpoint_id[]' value='{{ $breakpoint->id }}'>
                        <input type='number' name='breakpoint_min[]' placeholder='eg. 720' value='{{ $breakpoint->min_width }}'><span class='unit'>px</span>&nbsp;<span class='dash'>&ndash;</span>&nbsp;<input type='number' name='breakpoint_max[]' placeholder='eg. 1260' value='{{ $breakpoint->max_width >= $max_width ? '' : $breakpoint->max_width }}'><span class='unit'>px</span>
                    </div>
                @endforeach
            </div>

            <div>
                <button class='button breakpoints-add'>Add breakpoint</button>
            </div>
        </div>

        <div class='field separated'>
            <input type='submit' value='Save'>
        </div>
    </form>

    <div class='breakpoints-form' style='display:none;' id='breakpoints-template'>
        <button class='remove' aria-label='Delete breakpoint'>&times;</button>
        <input type='hidden' name='breakpoint_id[]'>
        <input type='number' name='breakpoint_min[]' placeholder='eg. 720'><span class='unit'>px</span>&nbsp;<span class='dash'>&ndash;</span>&nbsp;<input type='number' name='breakpoint_max[]' placeholder='eg. 1260'><span class='unit'>px</span>
    </div>

@stop


@section('footer.javascripts')

    <script src='https://code.jquery.com/jquery-1.12.3.min.js'></script>
    <script>

        var $field      = $('.field.breakpoints'),
            $list       = $('.breakpoints-list'),
            $template   = $('#breakpoints-template');

        $('#module').on('change', function(e) {
            var module = $(this).find('option:selected').text();
            if(module === 'MouseTracker') {
                $field.removeClass('hidden');
            }
            else {
                $field.addClass('hidden');
            }
        });

        $('.breakpoints-add').on('click', function(e) {
            e.preventDefault();

            $template
                .clone()
                .removeAttr('id')
                .css('display', 'block')
                .appendTo($list);
        });

        $list.on('click', '.remove', function(e) {
            e.preventDefault();
            $(this).parents('.breakpoints-form').remove();
        });
    </script>
@stop

resources/views/pages/site/index.blade.php
@extends('layouts.admin')

@section('meta.title') - Sites @stop
@section('header.title')<span class='sub'>Sites</span>@stop

@section('header.navigation')

    <ul>
        <li><a href='{{ route('admin.site.create') }}'>Add site</a></li>
    </ul>

@stop

@section('content')

    <h1>Sites list</h1>

    <h2>MouseTracker</h2>

    <table class='data'>
        <thead>
            <tr>
                <th class='index'>#</th>
                <th>Site title / url</th>
                <th class='actions'>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if($mouse->count() === 0) 
                <tr>
                    <td colspan='3' class='data-no-rows'>No sites being tracked. <a href='{{ route('admin.site.create') }}'>Add first site</a></td>
                </tr>
            @endif

            <?php $index = 1; ?>

            @foreach($mouse as $site)
                <tr>
                    <td class='index'>{{ $index++ }}</td>
                    <td>
                        {{ $site->title }}
                        <span class='url'>{{ $site->url }}</span>
                    </td>
                    <td class='actions'>
                        <a href='{{ route('admin.site.click', $site->id) }}'>View</a>
                        <a href='{{ route('admin.site.code', $site->id) }}'>Code</a>
                        <a href='{{ route('admin.site.edit', $site->id) }}'>Edit</a>
                        <form action='{{ route('admin.site.destroy', $site->id) }}' method='post'>
                            <input type='hidden' name='_method' value='DELETE'>
                            <input type='hidden' name='_token' value='{{ csrf_token() }}'>
                            <button class='danger'>Remove</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>FormTracker</h2>

    <table class='data'>
        <thead>
            <tr>
                <th class='index'>#</th>
                <th>Site title / url</th>
                <th class='actions'>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if($form->count() === 0) 
                <tr>
                    <td colspan='3' class='data-no-rows'>No sites being tracked. <a href='{{ route('admin.site.create') }}'>Add first site</a></td>
                </tr>
            @endif

            <?php $index = 1; ?>

            @foreach($form as $site)
                <tr>
                    <td class='index'>{{ $index++ }}</td>
                    <td>
                        {{ $site->title }}
                        <span class='url'>{{ $site->url }}</span>
                    </td>
                    <td class='actions'>
                        <a href='{{ route('admin.site.form', $site->id) }}'>View</a>
                        <a href='{{ route('admin.site.code', $site->id) }}'>Code</a>
                        <a href='{{ route('admin.site.edit', $site->id) }}'>Edit</a>
                        <a href='{{ route('admin.site.destroy', $site->id) }}' class='danger'>Remove</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

@stop